version: '3'

services:
    db:
        image: postgres:latest
        container_name: postgres
        environment:
          - POSTGRES_DB=proxydb
          - POSTGRES_USER=danny
          - POSTGRES_PASSWORD=123
        ports:
            - "5432:5432"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    proxy-app:
        build: .
        container_name: proxy-app