version: '3'

services:
    db:
        image: postgres:latest
        container_name: postgres
        environment:
            - TZ=Europe/Amsterdam
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_ENVIRONMENT=${ENVIRONMENT}
        ports:
            - "5432:5432"
        volumes:
            - ./docker-compose-scripts:/docker-entrypoint-initdb.d
    proxy-scraper-checker:
        build:
            context: ./src
        container_name: proxy-scraper-checker
        environment:
            - TZ=Europe/Amsterdam
            - PSC_ENVIRONMENT=${ENVIRONMENT}
            - PSC_DBPASSWORD=${POSTGRES_PASSWORD}
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
                max-file: "2"