version: '3'

services:
    db:
        image: postgres:latest
        container_name: postgres
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    proxy-scraper-checker:
        build: .
        container_name: proxy-scraper
        environment:
            - PSC_SETTINGS=Development
            - PSC_DBPASSWORD=${POSTGRES_PASSWORD}