version: '3'

services:
    db:
        image: postgres:latest
        container_name: postgres
        environment:
          - POSTGRES_DB=${POSTGRES_DB}
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - PSC-SETTINGS=Development
        ports:
            - "5432:5432"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    proxy-scraper:
        build: .
        container_name: proxy-scraper